### ISSUE TITLE
Make Ciao a pip installable package

### ISSUE THREAD

**Issue by scls19fr** [arduino-org/Ciao#3]
Hello,

it will be nice if Ciao could be a pip installable package

this document could help
http://python-packaging-user-guide.readthedocs.org/

Kind regards

**Comment by sergiotomasello** [comment]
Hi @scls19fr, *pip* is available on Linino OS, you can install it by run few commands:
```shell
opkg update
opkg install python-pip
```
Anyway **Ciao** is a software that only runs in **Linino OS** and it's closely related to the on-board microcontroller unit (MCU). It would not make sense to install it in others systems and we prefered to use the native package manager called *opkg* for distributing it and **Ciao Connectors**.
```shell
opkg update
opkg install ciao
```

Let me know your ideas and what do you think about

Regards

**Comment by scls19fr** [comment]
Thanks
